openapi: 3.0.0
info:
  title: Bitpowr Reference Account Staking API
  contact: {}
  version: '1.0'
  x-apievangelist-source: reconstructed from docs.bitpowr.com ReadMe per-operation OpenAPI fragments (2026-07-18)
servers:
- url: https://developers.bitpowr.com/api/v1
tags:
- name: Staking
paths:
  /staking:
    post:
      tags:
      - Staking
      summary: Create a new stake
      description: This endpoint creates a new stake on any supported chain. Currently we only support tron
      operationId: createstake
      parameters: []
      requestBody:
        content:
          application/json:
            encoding: {}
            schema:
              required:
              - fromAddress
              - accountId
              - chain
              - amount
              type: object
              properties:
                fromAddress:
                  type: string
                  description: The address you want to stake from
                  example: Tvweer....
                amount:
                  type: string
                  description: The amount you want to stake or delegate. Pass 0 for withdrawFrozenAsset operation
                  example: '200'
                chain:
                  type: string
                  description: The chain you are staking on. Currently only TRON
                  example: TRON
                accountId:
                  type: string
                  description: The account/wallet id you want to stake on
                  example: 12883-23833-
                operation:
                  type: string
                  description: The staking operation. Currently support - freezeTron, unFreezeTron, withdrawFrozenAsset, delegateResource, undelegateResource
                  example: freezeTron
                resource:
                  type: string
                  description: The resource you are looking to obtain from the stake. Currently BANDWIDTH and ENERGY
                  example: BANDWIDTH
                receiverAddress:
                  type: string
                  description: The address you want to delegate to
                  example: Tvweer....
        required: false
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                title: createstake
                required:
                - status
                - data
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    required:
                    - transaction
                    properties:
                      stake:
                        type: object
                      transaction:
                        title: Createtransactions
                        required:
                        - status
                        - data
                        type: object
                        properties:
                          status:
                            type: string
                          data:
                            title: Data2
                            required:
                            - hash
                            - status
                            - amount
                            - uid
                            - assetType
                            - chain
                            - fee
                            - ref
                            type: object
                            properties:
                              hash:
                                type: string
                              status:
                                type: string
                              amount:
                                type: string
                              uid:
                                type: string
                              assetType:
                                type: string
                              chain:
                                type: string
                              fee:
                                type: string
                              ref:
                                type: string
                            example:
                              hash: 1b6dff5b430a8b0b4bc604a23dda5aa4d7979dd11dbc25d9345bd88889ad8297
                              status: PENDING
                              amount: '0.00012741'
                              uid: 6680c116-c803-4e46-aa99-2f261cd216ac
                              assetType: BTC
                              chain: BITCOIN
                              fee: '0.00003034'
                              ref: BTP-Up5Ubzb0ot#H4LtW2VbdrxoxMt7Wy1
                        example:
                          status: success
                          data:
                            hash: 1b6dff5b430a8b0b4bc604a23dda5aa4d7979dd11dbc25d9345bd88889ad8297
                            status: PENDING
                            amount: '0.00012741'
                            uid: 6680c116-c803-4e46-aa99-2f261cd216ac
                            assetType: BTC
                            chain: BITCOIN
                            fee: '0.00003034'
                            ref: BTP-Up5Ubzb0ot#H4LtW2VbdrxoxMt7Wy1
                example:
                  status: success
                  data:
                    transaction: {}
                    stake: {}
              example:
                status: success
                data:
                  transaction: {}
                  stake: {}
      deprecated: false
      security:
      - bearer: []
    get:
      tags:
      - Staking
      summary: Get all stakes
      description: This endpoints gets all staking accounts and stakes
      operationId: getstakes
      parameters:
      - name: perPage
        in: query
        description: The number of staking per request.
        required: false
        style: form
        schema:
          type: number
          example: 1
      - name: page
        in: query
        description: The page offset
        required: false
        style: form
        schema:
          type: number
          example: 1
      - name: orderBy
        in: query
        description: Sort customers by asc or desc.
        required: false
        style: form
        schema:
          type: string
          example: asc
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                title: getstakes
                required:
                - page
                - totalPages
                - data
                type: object
                properties:
                  page:
                    type: number
                  totalPages:
                    type: number
                  data:
                    type: object
                example:
                  page: 1
                  totalPages: 200
                  data: []
              example:
                status: success
                page: '1'
                totalPages: 1
                data:
                - id: 21
                  uid: 978f61c2-9875-4e96-aa18-fbfcb811cb25
                  guid: 9ec59c3b-1bf8-497e-9838-dba378e3df46
                  label: Stake Account - TU72q8M35izYZRTYbUm8uTPEVWZ1PiB8uF
                  chain: TRON
                  activeStakeAmount: null
                  accountAddress: TU72q8M35izYZRTYbUm8uTPEVWZ1PiB8uF
                  mode: TEST
                  resources:
                    tron: '1.430846'
                    energy: 0
                    bandwidth: 0
                    energyTrxWeight: 0
                    bandwidthTrxWeight: 0
                  accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                  organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                  createdAt: '2024-04-03T11:48:42.980Z'
                  updatedAt: '2024-04-16T20:35:29.177Z'
                  Stake:
                  - id: 103
                    uid: e119219f-14b8-43fe-bf51-1ed92a0a8778
                    guid: ed898291-30c5-490e-a858-ce6ca0c6cb4a
                    status: STAKED
                    action: STAKE
                    amount: '1'
                    address: TU72q8M35izYZRTYbUm8uTPEVWZ1PiB8uF
                    chain: TRON
                    resource: BANDWIDTH
                    withdrawalAvailableAt: '2024-04-17T11:48:47.746Z'
                    mode: TEST
                    transactionId: f84d7b1a-30d1-4e8d-bf56-2a0f0bafcebc
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: 978f61c2-9875-4e96-aa18-fbfcb811cb25
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-04-03T11:48:47.748Z'
                    updatedAt: '2024-04-03T11:51:00.799Z'
                - id: 20
                  uid: e4667205-3cf3-4448-8d2b-9ea9a3d629c9
                  guid: 945e7e7f-8a27-4970-8572-b244b08fc406
                  label: Stake Account - TVEfg5ni5YwDqYk2DRkJUvthGRfEXhZAdf
                  chain: TRON
                  activeStakeAmount: null
                  accountAddress: TVEfg5ni5YwDqYk2DRkJUvthGRfEXhZAdf
                  mode: TEST
                  resources:
                    tron: '0.00019'
                    energy: 0
                    bandwidth: 0
                    energyTrxWeight: 0
                    bandwidthTrxWeight: 0
                  accountId: 35908ae4-9bdf-44df-877a-c2d14f30e28f
                  organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                  createdAt: '2024-03-22T06:15:20.459Z'
                  updatedAt: '2024-04-16T20:33:28.455Z'
                  Stake: []
                - id: 17
                  uid: fec7da7a-bb43-46f2-88eb-9393be4a410f
                  guid: 233b7f4a-6ef9-4e07-89f0-1658cd6fb80e
                  label: Stake Account - TGmsd9SQdDoMamkzKAAgJe77zoxcEuXdyz
                  chain: TRON
                  activeStakeAmount: null
                  accountAddress: TGmsd9SQdDoMamkzKAAgJe77zoxcEuXdyz
                  mode: TEST
                  resources:
                    tron: '1.090777'
                    energy: 0
                    bandwidth: 0
                    energyTrxWeight: 0
                    bandwidthTrxWeight: 0
                  accountId: d2acaff2-554d-4a7e-8c60-a3f8105c9f32
                  organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                  createdAt: '2024-03-08T09:17:08.165Z'
                  updatedAt: '2024-04-16T20:33:27.720Z'
                  Stake:
                  - id: 53
                    uid: d3104545-3134-43b3-9f7b-ef5d12549b21
                    guid: 78355a6a-3bb1-4cdb-ab69-c4e513a3233f
                    status: PENDING
                    action: STAKE
                    amount: '0.72674419'
                    address: TGmsd9SQdDoMamkzKAAgJe77zoxcEuXdyz
                    chain: TRON
                    resource: BANDWIDTH
                    withdrawalAvailableAt: '2024-03-22T09:17:12.661Z'
                    mode: TEST
                    transactionId: 9ab5ccac-5767-4c0b-a27f-69a7664074ad
                    accountId: d2acaff2-554d-4a7e-8c60-a3f8105c9f32
                    stakeAccountId: fec7da7a-bb43-46f2-88eb-9393be4a410f
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-08T09:17:12.663Z'
                    updatedAt: '2024-03-08T09:17:12.664Z'
                  - id: 62
                    uid: 6654460f-2b3b-4f2e-9a72-e31a005c4f3c
                    guid: 760155d6-ba62-45f1-be3d-2687cabb623f
                    status: FAILED
                    action: STAKE
                    amount: '0.75815011'
                    address: TGmsd9SQdDoMamkzKAAgJe77zoxcEuXdyz
                    chain: TRON
                    resource: BANDWIDTH
                    withdrawalAvailableAt: '2024-03-26T09:23:57.073Z'
                    mode: TEST
                    transactionId: 9e20ab91-405e-44d0-9fc3-2f70354409ea
                    accountId: d2acaff2-554d-4a7e-8c60-a3f8105c9f32
                    stakeAccountId: fec7da7a-bb43-46f2-88eb-9393be4a410f
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-12T09:23:57.076Z'
                    updatedAt: '2024-03-12T09:24:07.396Z'
                - id: 12
                  uid: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                  guid: a7ace9a6-a316-4138-b173-6498cdf780f1
                  label: Stake Account - TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                  chain: TRON
                  activeStakeAmount: null
                  accountAddress: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                  mode: TEST
                  resources:
                    tron: '1.125261'
                    energy: 211
                    bandwidth: 0
                    energyTrxWeight: 2.38318414900526
                    bandwidthTrxWeight: 0
                  accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                  organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                  createdAt: '2024-03-07T09:13:55.692Z'
                  updatedAt: '2024-04-16T20:37:29.826Z'
                  Stake:
                  - id: 44
                    uid: 82f379b5-acf2-4e38-9ea3-10f8e4dac029
                    guid: 813a6a1a-2cc0-45ad-b30c-81aed084e43e
                    status: PENDING
                    action: STAKE
                    amount: ' 0.72568940'
                    address: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                    chain: TRON
                    resource: BANDWIDTH
                    withdrawalAvailableAt: '2024-03-07T09:14:02.216Z'
                    mode: TEST
                    transactionId: 4da689db-9aec-41ff-b5d6-de4b2c7fee60
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-07T09:14:02.218Z'
                    updatedAt: '2024-03-07T09:14:02.219Z'
                  - id: 63
                    uid: dc00de0e-c5b4-43ea-bf03-918e8f16c5fc
                    guid: c2cf31d0-ff8f-42bc-9dea-c249d3050201
                    status: FAILED
                    action: STAKE
                    amount: '0.75642965'
                    address: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                    chain: TRON
                    resource: BANDWIDTH
                    withdrawalAvailableAt: '2024-03-26T09:29:09.128Z'
                    mode: TEST
                    transactionId: 69b17bdd-6095-47e3-86df-7f350f2d92c1
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-12T09:29:09.131Z'
                    updatedAt: '2024-03-12T09:29:12.804Z'
                  - id: 81
                    uid: ede0df85-9f4a-4e44-84a9-8d25ba1f4c09
                    guid: e61e5fd7-9a91-401f-98c7-adc005403ad4
                    status: STAKED
                    action: STAKE
                    amount: '2.38473768'
                    address: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                    chain: TRON
                    resource: ENERGY
                    withdrawalAvailableAt: '2024-04-01T11:39:03.630Z'
                    mode: TEST
                    transactionId: 69916e8a-190c-4fcc-a971-5ca39ba87d90
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-18T11:39:03.637Z'
                    updatedAt: '2024-03-18T11:41:17.605Z'
                  - id: 85
                    uid: 27edf6e0-efa1-415e-821e-af31c1b6b97b
                    guid: f4e03252-37ab-4b05-8dc1-94181e6d3136
                    status: STAKED
                    action: STAKE
                    amount: '1'
                    address: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                    chain: TRON
                    resource: ENERGY
                    withdrawalAvailableAt: '2024-04-02T10:05:23.848Z'
                    mode: TEST
                    transactionId: 3e568d41-dcd5-4c8a-b37e-c78a1429a1bb
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-19T10:05:23.850Z'
                    updatedAt: '2024-03-19T10:05:39.741Z'
                  - id: 86
                    uid: 07ed70d8-74fa-46d3-9271-4b0ff865c465
                    guid: 226b420b-6349-434e-86f8-a33ca7757857
                    status: UNSTAKING
                    action: UNSTAKE
                    amount: '1'
                    address: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                    chain: TRON
                    resource: ENERGY
                    withdrawalAvailableAt: '2024-04-02T10:06:10.249Z'
                    mode: TEST
                    transactionId: 701e96e8-c340-428c-9003-8867195fd04d
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-19T10:06:10.252Z'
                    updatedAt: '2024-03-19T10:06:19.544Z'
                  - id: 87
                    uid: d05240f3-12e9-45a3-9b20-e5aea209a176
                    guid: 9e4da10c-a334-45b8-92c7-ac7a88301619
                    status: FAILED
                    action: UNSTAKE
                    amount: '1'
                    address: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                    chain: TRON
                    resource: ENERGY
                    withdrawalAvailableAt: '2024-04-02T10:06:52.740Z'
                    mode: TEST
                    transactionId: 07443a2d-18ef-4993-b98d-bbf705faa0d3
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-19T10:06:52.741Z'
                    updatedAt: '2024-03-19T10:06:56.892Z'
                  - id: 100
                    uid: 386913b7-ad3a-4f46-bcef-bd208faacaf3
                    guid: 12e21c32-7bd6-4c2b-b99e-b9753b68bb9f
                    status: FAILED
                    action: UNSTAKE
                    amount: '0.75642965'
                    address: TH3Svsj96ktiARDEE4mPybypoFaugXbjLG
                    chain: TRON
                    resource: BANDWIDTH
                    withdrawalAvailableAt: '2024-04-12T11:39:09.760Z'
                    mode: TEST
                    transactionId: e581e92a-d097-42dd-beb5-2eef802e1b49
                    accountId: f422f7f8-23d5-4dd9-8a62-46c851ddddde
                    stakeAccountId: babdd6c0-5883-4db7-9b53-fb175e3f9c8a
                    organizationId: 0ed32cca-14b2-4fd0-8221-bd1c4e752198
                    createdAt: '2024-03-29T11:39:09.761Z'
                    updatedAt: '2024-03-29T11:39:17.695Z'
      deprecated: false
      security:
      - bearer: []
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
